export const Categories = [
    {
        id:1,
        name:"All",
        icon:"shopping-cart"
    },
    {
        id:2,
        name:"Laptops",
        icon:"laptop"
    },
    {
        id:3,
        name:"Gadgets",
        icon:"car-battery"
    },
    {
        id:4,
        name:"Shoes",
        icon:"shoe-prints"
    },
    {
        id:5,
        name:"Cloths",
        icon:"shirt"
    },
    {
        id:6,
        name:"TV's And Computers",
        icon:"television"
    },
    {
        id:7,
        name:"Mobiles",
        icon:"mobile"
    },
    {
        id:8,
        name:"Kitchen",
        icon:"kitchen-set"
    },
    {
        id:9,
        name:"Cars",
        icon:"car"
    },
    {
        id:10,
        name:"Sports",
        icon:"football"
    },
    {
        id:11,
        name:"Cameras",
        icon:"camera"
    },
]